import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter, STIX_Two_Text } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const stixTwoText = STIX_Two_Text({
  variable: '--font-stix-two-text',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${stixTwoText.variable} antialiased min-h-screen max-w-screen p-6`}
      >
        {children}
        <div className='hidden md:block fixed bottom-88 right-4 -rotate-90 origin-bottom-right text-5xl text-muted opacity-20 font-stix-two-text'>
          Morgan Selbekk
        </div>
        {/* <div className='hidden md:block fixed bottom-180 right-4 -rotate-90 origin-bottom-right text-8xl text-muted opacity-20'>
          Morgan Selbekk
        </div> */}
      </body>
    </html>
  );
}
